
<div class="container">

	<h3 class="titre">Gestion des Véhicules</h3>

 	<table class="table table-bordered table-striped" id="ancre_filtre">
 		<tr>
 			<th>Véhicules</th>
 			<th>Agence</th>
 			<th>Titre</th>
 			<th>Marque</th>
 			<th>Modèle</th>
 			<th>Description</th>
 			<th>Photo</th>
 			<th>Prix</th>
 			<th>Actions</th>
 		</tr>

 		<?php foreach ($vehicule as $key => $valeur): ?>

 			<tr>
 				<td><?= $valeur['id_vehicule']; ?></td>
 				<td><?= $valeur['ville']; ?></td>
 				<td><?= $valeur['titre']; ?></td>
 				<td><?= $valeur['marque']; ?></td>
 				<td><?= $valeur['modele']; ?></td>
 				<td><?= $valeur['description']; ?></td>
 				<td>
 					<img class="w-50" src="<?= RACINE_SITE.'/utilities/img/'. $valeur['photo']; ?>">
 				</td>
 				<td><?= $valeur['prix_journalier']; ?></td>
 				<td>
					<a href="?action=modification&id=<?= $valeur['id_vehicule'] ?>#ancre_modif">
						<i class="fas fa-pen"></i>
					</a> 
					-  
					<a href="?action=suppression&id=<?= $valeur['id_vehicule'] ?>">
						<i class="fas fa-trash-alt"></i>
					</a> 
				</td>
 			</tr>

 		<?php endforeach; ?>

 	</table>

 	<hr>

 	<!-- Fomulaire gestion véhicule -->
 	<h4 class="titre">Ajout/Modif d'un véhicule</h4>


 			<div class="form-group col-2">
 				<div class="input-group">

 					<select class="form-control" name="id_agence" id="filtre">


 						<?php foreach( liste_agence() as $key => $value ): ?>

 							<option value="<?= $value['id_agence']; ?>"<?= isset($vehicule_actuel['id_agence']) && $vehicule_actuel['id_agence'] == $value['id_agence'] ? 'selected' : '' ?>
 							href="?action=filtre_agence&id_agence=<?= $value['id_agence'] ?>#ancre_filtre">
 								<?= $value['titre']; ?>
 							</option>
 							
 						<?php endforeach; ?>
 					</select>

 				</div>
 			</div>
 		</div>

 		<div class="row">
 			<div class="form-group col-6">
 				<label>Titre</label>
 				<div class="input-group">
 					<input type="text" name="titre" placeholder="Titre de l'annonce" class="form-control" value="<?= $vehicule_actuel['titre'] ?? '' ?>">
 				</div>
 			</div>

 			<div class="form-group col-6">
 				<label>Marque</label>
 				<div class="input-group">
 					<input type="text" name="marque" placeholder="Marque" class="form-control" value="<?= $vehicule_actuel['marque'] ?? '' ?>">
 				</div>
 			</div>
 		</div>


 		<div class="row">
 			<div class="form-group col-6">
 				<label>Description</label>
 				<div class="input-group">
 					<textarea name="desc" placeholder="Description de l'annonce" class="form-control"><?= $vehicule_actuel['description'] ?? '' ?></textarea>
 				</div>
 			</div>

 			<div class="form-group col-6">
 				<label>Modèle</label>
 				<div class="input-group">
 					<input type="text" name="modele" placeholder="Modèle" class="form-control" value="<?= $vehicule_actuel['modele'] ?? '' ?>">
 				</div>
 			</div>
 		</div>


 		<div class="row">
 			<div class="form-group col-6">
 				<label>Photo</label>
 				<div class="input-group">
 					<input type="file" name="photo" class="form-control" value="<?= $vehicule_actuel['photo'] ?? '' ?>">
 				</div>
 				<?php if( !empty($vehicule_actuel['photo']) ) :?>

 					<img class="img_tab" src="<?= RACINE_SITE . 'utilities/img/'.$vehicule_actuel['photo'] ?>">
 					<input type="hidden" name="photo_actuelle" value="<?= $vehicule_actuel['photo']; ?>">
 					
 				<?php endif; ?>

 			</div>

 			<div class="form-group col-6">
 				<label>Prix</label>
 				<div class="input-group">
 					<input type="number" name="prix" placeholder="Prix journalier" class="form-control" value="<?= $vehicule_actuel['prix_journalier'] ?? '' ?>">
 				</div>
 			</div>
 		</div>
 		
 		<div class="form-group col-6">
	    	<div><label><br></label></div>
	    	<input type="submit" name="inscription" value="Enregistrer" class="btn btn-primary">
	    	<input type="reset" class="btn btn-secondary">
	    </div>

	</form>

</div>

<script type="text/javascript" src="<?= RACINE_SITE . 'utilities/js/redirect.js' ?>"></script>
