
<div class="container">
	<h3 class="titre">Gestion des Commandes</h3>

	<select id="filtre" class="mb-2 bg-light">
	<option>Commande par Agence</option>
	<?php foreach( liste_agence() as $cle => $valeur ): ?>
		<option href="?action=filtre_commande&agence=<?= $valeur['id_agence']; ?>"><?= $valeur['titre']; ?></option>
	<?php endforeach; ?>
	</select>

	<?php if( $historique_loca ): ?>
		<table class="table table-bordered table-striped">
			<thead class="thead-dark">
				<tr>
					<th>Loc Num</th>
					<th>Véhicule</th>
					<th>Agence</th>
					<th>Début</th>
					<th>Fin</th>
					<th>Prix</th>
					<th>Jours</th>
					<th>Statut</th>
					<th>Client</th>
				</tr>
			</thead>
			<?php foreach( $historique_loca as $cle => $valeur ): ?>
				<?php $nbj = nbjour( $valeur['date_heure_depart'], $valeur['date_heure_fin'] ); 
					 
				?>
				<tr>
					<td> <?= $numLoc++; ?> </td>
					<td> <?= $valeur['marque']; ?> </td>
					<td> <?= $valeur['ville']; ?> </td>
					<td> <?= $valeur['date_heure_depart']; ?> </td>
					<td> <?= $valeur['date_heure_fin']; ?> </td>
					<td> <?= $valeur['prix_total']; ?> </td>
					<td> <?= $nbj; ?> </td>
					<td> <?= encours( $valeur['date_heure_fin'] ); ?> </td>
					<td> <a href="<?= RACINE_SITE.'admin/gestion_membre.php' ?>"><?= $valeur['prenom'] ?></a>  </td>
				</tr>
			<?php endforeach; ?>

		</table>
	<?php else: ?>
		<h3 class="titre text-center">Aucune commande enregistrée !!</h3>
	<?php endif; ?>
	
</div>

<script type="text/javascript" src="<?= RACINE_SITE . 'utilities/js/redirect.js' ?>"></script>