
<div class="container"> 

  <div class="row">
    <div class="form-group  col-2">

      <select class="form-control text-center bg-light" id="filtre">
        <option>-- filtre --</option>
        <option href="?action=filtre&ordre=asc#ancre_modif">prix croissant</option>
        <option href="?action=filtre&ordre=desc#ancre_modif">prix décroissant</option>
      </select>

    </div>
  </div>

  <div class="row card-columns">
      <?php if ( $vehicules->rowCount() > 0 ) : ?>
       
         <?php while( $vehicule = $vehicules->fetch(PDO::FETCH_ASSOC) ): ?>

          	<?php   extract($vehicule); ?>	

            <div class="accueil_vehicule card text-center col-3 pb-2" id="ancre_modif">
              
          		<?php if(!empty($photo)): ?>

                <div>
                  <img src="<?= RACINE_SITE . 'utilities/img/' . $photo ?>" alt="<?= $titre ?>">
                </div>

               <?php endif; ?>  

               <div><strong><?= $titre ?></strong></div>
              
               <?= $description ?>
              
               <div><?= $prix_journalier ?> € / jour</div>
               <div> <?= $titreagence ?></div>
               <br>
               <a href="<?= RACINE_SITE .'reservation.php?reservation='.$id_vehicule ?>" class="btn btn-success <?= enLocation($id_vehicule) ? 'disabled' : '' ?>">
                  Réserver
               </a>
      		
            </div>

         <?php endwhile; ?>

      <?php else : ?>

         <p colspan="6">Pas encore de véhicules enregistrés!!</p>

      <?php endif; ?>

   </div>
</div>
