

	<div class="container">
		
		<div class="row">
			<div class="col-2 mt-5"><?= $reservation['marque'].' - '.$reservation['modele']; ?>
			<br>
			Prix journalier <?= $reservation['prix_journalier']; ?></div>
			<div class="col-3"><img src="<?= RACINE_SITE.'utilities/img/'. $reservation['photo']; ?>"></div>
		</div>

		<form class="formulaire" method="post" action="">

			<input type="hidden" name="id_membre" value="<?= $_SESSION['membre']['id_membre']; ?>">
			<input type="hidden" name="id_vehicule" value="<?= $reservation['id_vehicule']; ?>">
			<input type="hidden" name="id_agence" value="<?= $reservation['id_agence']; ?>">
			<input type="hidden" id="pttc" name="pttc" value="<?= $reservation['prix_journalier']; ?>">

			<div class="row">
				<div class="form-group col-3">
					<label>Date de début</label>
					<div class="input-group">
						<input type="date" name="date_debut" min="<?= date("Y-m-d"); ?>" id="date_debut" class="form-control">
					</div>
				</div>
				<div class="form-group col-3">
					<label>Date de fin</label>
					<div class="input-group">
						<input type="date" name="date_fin" min=""  max="" id="date_fin" class="form-control" disabled="disabled">
					</div>
				</div>
				<!--  --> 
			</div>
			<div class="row">
				<div class="col-6 text-center">
					<strong id="prix"></strong>
				</div>
			</div>
			<p></p>
			<div class="row">
				<div class="col-3">
					<input type="submit" value="Réserver" class="btn btn-primary">
	    			<input type="reset" class="btn btn-secondary">
				</div>
			</div>
		</form>
	</div>

	<script type="text/javascript" src="<?= RACINE_SITE.'utilities/js/prix.js' ?>"></script>
